# Generated by Django 2.2 on 2019-08-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TildaArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilda_content', models.TextField(blank=True, verbose_name='HTML-код статьи')),
                ('styles', models.TextField(blank=True, verbose_name='Стили')),
                ('scripts', models.TextField(blank=True, verbose_name='Скрипты')),
                ('archive', models.FileField(blank=True, null=True, upload_to='tilda', verbose_name='Импорт из файла')),
            ],
            options={
                'verbose_name': 'статья (Тильда)',
                'verbose_name_plural': 'статьи (Тильда)',
            },
        ),
    ]
